### ISSUE TITLE
bad results

### ISSUE THREAD

**Issue by loboere** [nosiu/InstantID-faceswap#1]
are you sure this works? I tried a black and white mask but the generated image is glitchy
Can you upload an example of how to use this?

**Comment by nosiu** [comment]
faceswap.py file is an example.
Running it should give you similar results to **Example 2** from  https://github.com/InstantID/InstantID/pull/89 

If there is one tip I can give is to keep the `resize` option True it slows the process, but instantID doesn't work well (from my experience) with 'small' faces.
If you are aiming for something more 'photorealistic' then you probably should download different SDXL checkpoint

Edit: I have almost ready a custom node for ComfyUI which does exactly that (swap faces) and allows you to inpaint the image on the fly. I will post the link here when I'm done with it.

**Comment by triplecookedchips** [comment]
Hey @nosiu - this looks great, any plans to add to replicate or huggingface in the near future?

**Comment by nosiu** [comment]
@triplecookedchips 
Link to custom node https://github.com/nosiu/comfyui-instantId-faceswap

I'm first time hearing about replicate and my relation with huggingface is very simple I treat it like a model repository (ez download nothing more). So who knows

**Comment by johndpope** [comment]
there's a lora on civitai I can't get to work with this - https://gist.github.com/johndpope/4c4ff9777a867fc4793f2278dba38e9f

	size mismatch for text_model.encoder.layers.11.self_attn.q_proj.lora_A.orgasmface.weight: copying a param with shape torch.Size([1, 768]) from checkpoint, the shape in current model is torch.Size([2, 768]). - does the lora need to be retained to work? 
https://civitai.com/models/152791/orgasm-face-sdxl
it works out of the box with this papercut sdxl model - only difference seems to be https://civitai.com/models/122567/papercut-sdxl



_Trained using https://github.com/TheLastBen/fast-stable-diffusion SDXL trainer._

**Comment by youjieWang** [comment]
@nosiu I use same code and same example, but I can't get the same result for your example. 
And there is an issue for your code
![image](https://github.com/nosiu/InstantID-faceswap/assets/43266020/0af40899-6ac1-4221-8796-61b591d1b601)

**Comment by youjieWang** [comment]
> @nosiu I use same code and same example, but I can't get the same result for your example. And there is an issue for your code ![image](https://private-user-images.githubusercontent.com/43266020/342609449-0af40899-6ac1-4221-8796-61b591d1b601.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTc5MzIsIm5iZiI6MTcxOTI5NzYzMiwicGF0aCI6Ii80MzI2NjAyMC8zNDI2MDk0NDktMGFmNDA4OTktNmFjMS00MjIxLTg3OTYtNjFiNTkxZDFiNjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA2NDAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZDM4NGZjYTVjZDgyYmNlZDllOWZmMjhlZTc2YTg5MmJiYmRlYTI2NjZlNDUwMDRiM2IyYTUwMTU3MTQ1ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aSZKwqViMHTfNJEJrNejglXQsGUhd5c15_MZVIqjWYU)

the result show behind
![image](https://github.com/nosiu/InstantID-faceswap/assets/43266020/ac4b3514-3def-4406-891b-5139281253df)

**Comment by nosiu** [comment]
@youjieWang Yes, it's hard to get the right parameters without any visual aids.
For that very reason, I made a plugin for Comfy, you can draw a mask and change parameters on the fly.

https://github.com/nosiu/comfyui-instantId-faceswap
