### ISSUE TITLE
Use both Inpainting and Canny edges

### ISSUE THREAD

**Issue by ashual** [nosiu/InstantID-faceswap#4]
Hi,
Can I use your script with multiple controlnet conditioning?
e.g. inpaint the face conditioning on canny-edges or depth?

Thanks for your response

**Comment by nosiu** [comment]
Hi, yes, technically it should work.
But to be honest I haven't tested it.

**Comment by ashual** [comment]
can you please guide me of where the extra condition should be added and where do I need to add the controlnet model?

**Comment by nosiu** [comment]
Something like that should work.
```python
controlnet = ControlNetModel.from_pretrained(controlnet_path, torch_dtype=torch.float16)
controlnet2 = ... # second controlnet

pipe = StableDiffusionXLInstantIDInpaintPipeline.from_pretrained(
  ...
  controlnet=[controlnet, controlnet2],
  ...
)
...
control_image2 = ...  # second control image

image = pipe(
  ...
  control_image=[control_image, control_image2],
  controlnet_conditioning_scale=[1.0,  0.8], 
  ...
)
```
